/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/student'
import { Route as AuthenticatedInstructorRouteImport } from './routes/_authenticated/instructor'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedStudentIndexRouteImport } from './routes/_authenticated/student.index'
import { Route as AuthenticatedInstructorIndexRouteImport } from './routes/_authenticated/instructor.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedStudentTechniquesRouteImport } from './routes/_authenticated/student.techniques'
import { Route as AuthenticatedStudentProfileRouteImport } from './routes/_authenticated/student.profile'
import { Route as AuthenticatedStudentClassesRouteImport } from './routes/_authenticated/student.classes'
import { Route as AuthenticatedStudentChampionshipsRouteImport } from './routes/_authenticated/student.championships'
import { Route as AuthenticatedInstructorTechniquesRouteImport } from './routes/_authenticated/instructor.techniques'
import { Route as AuthenticatedInstructorClassesRouteImport } from './routes/_authenticated/instructor.classes'
import { Route as AuthenticatedInstructorAttendanceRouteImport } from './routes/_authenticated/instructor.attendance'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminChampionshipsRouteImport } from './routes/_authenticated/admin.championships'
import { Route as AuthenticatedAdminBranchesRouteImport } from './routes/_authenticated/admin.branches'
import { Route as AuthenticatedInstructorStudentsIndexRouteImport } from './routes/_authenticated/instructor.students.index'
import { Route as ApiPublicHooksStudentOfMonthRouteImport } from './routes/api/public/hooks/student-of-month'
import { Route as AuthenticatedInstructorStudentsStudentIdRouteImport } from './routes/_authenticated/instructor.students.$studentId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInstructorRoute = AuthenticatedInstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedInstructorIndexRoute =
  AuthenticatedInstructorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInstructorRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedStudentTechniquesRoute =
  AuthenticatedStudentTechniquesRouteImport.update({
    id: '/techniques',
    path: '/techniques',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentProfileRoute =
  AuthenticatedStudentProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentClassesRoute =
  AuthenticatedStudentClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentChampionshipsRoute =
  AuthenticatedStudentChampionshipsRouteImport.update({
    id: '/championships',
    path: '/championships',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedInstructorTechniquesRoute =
  AuthenticatedInstructorTechniquesRouteImport.update({
    id: '/techniques',
    path: '/techniques',
    getParentRoute: () => AuthenticatedInstructorRoute,
  } as any)
const AuthenticatedInstructorClassesRoute =
  AuthenticatedInstructorClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AuthenticatedInstructorRoute,
  } as any)
const AuthenticatedInstructorAttendanceRoute =
  AuthenticatedInstructorAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedInstructorRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminChampionshipsRoute =
  AuthenticatedAdminChampionshipsRouteImport.update({
    id: '/championships',
    path: '/championships',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBranchesRoute =
  AuthenticatedAdminBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedInstructorStudentsIndexRoute =
  AuthenticatedInstructorStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedInstructorRoute,
  } as any)
const ApiPublicHooksStudentOfMonthRoute =
  ApiPublicHooksStudentOfMonthRouteImport.update({
    id: '/api/public/hooks/student-of-month',
    path: '/api/public/hooks/student-of-month',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedInstructorStudentsStudentIdRoute =
  AuthenticatedInstructorStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => AuthenticatedInstructorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/instructor': typeof AuthenticatedInstructorRouteWithChildren
  '/student': typeof AuthenticatedStudentRouteWithChildren
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/championships': typeof AuthenticatedAdminChampionshipsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/instructor/attendance': typeof AuthenticatedInstructorAttendanceRoute
  '/instructor/classes': typeof AuthenticatedInstructorClassesRoute
  '/instructor/techniques': typeof AuthenticatedInstructorTechniquesRoute
  '/student/championships': typeof AuthenticatedStudentChampionshipsRoute
  '/student/classes': typeof AuthenticatedStudentClassesRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/student/techniques': typeof AuthenticatedStudentTechniquesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/instructor/': typeof AuthenticatedInstructorIndexRoute
  '/student/': typeof AuthenticatedStudentIndexRoute
  '/instructor/students/$studentId': typeof AuthenticatedInstructorStudentsStudentIdRoute
  '/api/public/hooks/student-of-month': typeof ApiPublicHooksStudentOfMonthRoute
  '/instructor/students/': typeof AuthenticatedInstructorStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/championships': typeof AuthenticatedAdminChampionshipsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/instructor/attendance': typeof AuthenticatedInstructorAttendanceRoute
  '/instructor/classes': typeof AuthenticatedInstructorClassesRoute
  '/instructor/techniques': typeof AuthenticatedInstructorTechniquesRoute
  '/student/championships': typeof AuthenticatedStudentChampionshipsRoute
  '/student/classes': typeof AuthenticatedStudentClassesRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/student/techniques': typeof AuthenticatedStudentTechniquesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/instructor': typeof AuthenticatedInstructorIndexRoute
  '/student': typeof AuthenticatedStudentIndexRoute
  '/instructor/students/$studentId': typeof AuthenticatedInstructorStudentsStudentIdRoute
  '/api/public/hooks/student-of-month': typeof ApiPublicHooksStudentOfMonthRoute
  '/instructor/students': typeof AuthenticatedInstructorStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/instructor': typeof AuthenticatedInstructorRouteWithChildren
  '/_authenticated/student': typeof AuthenticatedStudentRouteWithChildren
  '/_authenticated/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/_authenticated/admin/championships': typeof AuthenticatedAdminChampionshipsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/instructor/attendance': typeof AuthenticatedInstructorAttendanceRoute
  '/_authenticated/instructor/classes': typeof AuthenticatedInstructorClassesRoute
  '/_authenticated/instructor/techniques': typeof AuthenticatedInstructorTechniquesRoute
  '/_authenticated/student/championships': typeof AuthenticatedStudentChampionshipsRoute
  '/_authenticated/student/classes': typeof AuthenticatedStudentClassesRoute
  '/_authenticated/student/profile': typeof AuthenticatedStudentProfileRoute
  '/_authenticated/student/techniques': typeof AuthenticatedStudentTechniquesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/instructor/': typeof AuthenticatedInstructorIndexRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexRoute
  '/_authenticated/instructor/students/$studentId': typeof AuthenticatedInstructorStudentsStudentIdRoute
  '/api/public/hooks/student-of-month': typeof ApiPublicHooksStudentOfMonthRoute
  '/_authenticated/instructor/students/': typeof AuthenticatedInstructorStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/instructor'
    | '/student'
    | '/admin/branches'
    | '/admin/championships'
    | '/admin/users'
    | '/instructor/attendance'
    | '/instructor/classes'
    | '/instructor/techniques'
    | '/student/championships'
    | '/student/classes'
    | '/student/profile'
    | '/student/techniques'
    | '/admin/'
    | '/instructor/'
    | '/student/'
    | '/instructor/students/$studentId'
    | '/api/public/hooks/student-of-month'
    | '/instructor/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/branches'
    | '/admin/championships'
    | '/admin/users'
    | '/instructor/attendance'
    | '/instructor/classes'
    | '/instructor/techniques'
    | '/student/championships'
    | '/student/classes'
    | '/student/profile'
    | '/student/techniques'
    | '/admin'
    | '/instructor'
    | '/student'
    | '/instructor/students/$studentId'
    | '/api/public/hooks/student-of-month'
    | '/instructor/students'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/instructor'
    | '/_authenticated/student'
    | '/_authenticated/admin/branches'
    | '/_authenticated/admin/championships'
    | '/_authenticated/admin/users'
    | '/_authenticated/instructor/attendance'
    | '/_authenticated/instructor/classes'
    | '/_authenticated/instructor/techniques'
    | '/_authenticated/student/championships'
    | '/_authenticated/student/classes'
    | '/_authenticated/student/profile'
    | '/_authenticated/student/techniques'
    | '/_authenticated/admin/'
    | '/_authenticated/instructor/'
    | '/_authenticated/student/'
    | '/_authenticated/instructor/students/$studentId'
    | '/api/public/hooks/student-of-month'
    | '/_authenticated/instructor/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicHooksStudentOfMonthRoute: typeof ApiPublicHooksStudentOfMonthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instructor': {
      id: '/_authenticated/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof AuthenticatedInstructorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/instructor/': {
      id: '/_authenticated/instructor/'
      path: '/'
      fullPath: '/instructor/'
      preLoaderRoute: typeof AuthenticatedInstructorIndexRouteImport
      parentRoute: typeof AuthenticatedInstructorRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/student/techniques': {
      id: '/_authenticated/student/techniques'
      path: '/techniques'
      fullPath: '/student/techniques'
      preLoaderRoute: typeof AuthenticatedStudentTechniquesRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/profile': {
      id: '/_authenticated/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof AuthenticatedStudentProfileRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/classes': {
      id: '/_authenticated/student/classes'
      path: '/classes'
      fullPath: '/student/classes'
      preLoaderRoute: typeof AuthenticatedStudentClassesRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/championships': {
      id: '/_authenticated/student/championships'
      path: '/championships'
      fullPath: '/student/championships'
      preLoaderRoute: typeof AuthenticatedStudentChampionshipsRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/instructor/techniques': {
      id: '/_authenticated/instructor/techniques'
      path: '/techniques'
      fullPath: '/instructor/techniques'
      preLoaderRoute: typeof AuthenticatedInstructorTechniquesRouteImport
      parentRoute: typeof AuthenticatedInstructorRoute
    }
    '/_authenticated/instructor/classes': {
      id: '/_authenticated/instructor/classes'
      path: '/classes'
      fullPath: '/instructor/classes'
      preLoaderRoute: typeof AuthenticatedInstructorClassesRouteImport
      parentRoute: typeof AuthenticatedInstructorRoute
    }
    '/_authenticated/instructor/attendance': {
      id: '/_authenticated/instructor/attendance'
      path: '/attendance'
      fullPath: '/instructor/attendance'
      preLoaderRoute: typeof AuthenticatedInstructorAttendanceRouteImport
      parentRoute: typeof AuthenticatedInstructorRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/championships': {
      id: '/_authenticated/admin/championships'
      path: '/championships'
      fullPath: '/admin/championships'
      preLoaderRoute: typeof AuthenticatedAdminChampionshipsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/branches': {
      id: '/_authenticated/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AuthenticatedAdminBranchesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/instructor/students/': {
      id: '/_authenticated/instructor/students/'
      path: '/students'
      fullPath: '/instructor/students/'
      preLoaderRoute: typeof AuthenticatedInstructorStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedInstructorRoute
    }
    '/api/public/hooks/student-of-month': {
      id: '/api/public/hooks/student-of-month'
      path: '/api/public/hooks/student-of-month'
      fullPath: '/api/public/hooks/student-of-month'
      preLoaderRoute: typeof ApiPublicHooksStudentOfMonthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/instructor/students/$studentId': {
      id: '/_authenticated/instructor/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/instructor/students/$studentId'
      preLoaderRoute: typeof AuthenticatedInstructorStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedInstructorRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBranchesRoute: typeof AuthenticatedAdminBranchesRoute
  AuthenticatedAdminChampionshipsRoute: typeof AuthenticatedAdminChampionshipsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBranchesRoute: AuthenticatedAdminBranchesRoute,
  AuthenticatedAdminChampionshipsRoute: AuthenticatedAdminChampionshipsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedInstructorRouteChildren {
  AuthenticatedInstructorAttendanceRoute: typeof AuthenticatedInstructorAttendanceRoute
  AuthenticatedInstructorClassesRoute: typeof AuthenticatedInstructorClassesRoute
  AuthenticatedInstructorTechniquesRoute: typeof AuthenticatedInstructorTechniquesRoute
  AuthenticatedInstructorIndexRoute: typeof AuthenticatedInstructorIndexRoute
  AuthenticatedInstructorStudentsStudentIdRoute: typeof AuthenticatedInstructorStudentsStudentIdRoute
  AuthenticatedInstructorStudentsIndexRoute: typeof AuthenticatedInstructorStudentsIndexRoute
}

const AuthenticatedInstructorRouteChildren: AuthenticatedInstructorRouteChildren =
  {
    AuthenticatedInstructorAttendanceRoute:
      AuthenticatedInstructorAttendanceRoute,
    AuthenticatedInstructorClassesRoute: AuthenticatedInstructorClassesRoute,
    AuthenticatedInstructorTechniquesRoute:
      AuthenticatedInstructorTechniquesRoute,
    AuthenticatedInstructorIndexRoute: AuthenticatedInstructorIndexRoute,
    AuthenticatedInstructorStudentsStudentIdRoute:
      AuthenticatedInstructorStudentsStudentIdRoute,
    AuthenticatedInstructorStudentsIndexRoute:
      AuthenticatedInstructorStudentsIndexRoute,
  }

const AuthenticatedInstructorRouteWithChildren =
  AuthenticatedInstructorRoute._addFileChildren(
    AuthenticatedInstructorRouteChildren,
  )

interface AuthenticatedStudentRouteChildren {
  AuthenticatedStudentChampionshipsRoute: typeof AuthenticatedStudentChampionshipsRoute
  AuthenticatedStudentClassesRoute: typeof AuthenticatedStudentClassesRoute
  AuthenticatedStudentProfileRoute: typeof AuthenticatedStudentProfileRoute
  AuthenticatedStudentTechniquesRoute: typeof AuthenticatedStudentTechniquesRoute
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
}

const AuthenticatedStudentRouteChildren: AuthenticatedStudentRouteChildren = {
  AuthenticatedStudentChampionshipsRoute:
    AuthenticatedStudentChampionshipsRoute,
  AuthenticatedStudentClassesRoute: AuthenticatedStudentClassesRoute,
  AuthenticatedStudentProfileRoute: AuthenticatedStudentProfileRoute,
  AuthenticatedStudentTechniquesRoute: AuthenticatedStudentTechniquesRoute,
  AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
}

const AuthenticatedStudentRouteWithChildren =
  AuthenticatedStudentRoute._addFileChildren(AuthenticatedStudentRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedInstructorRoute: typeof AuthenticatedInstructorRouteWithChildren
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedInstructorRoute: AuthenticatedInstructorRouteWithChildren,
  AuthenticatedStudentRoute: AuthenticatedStudentRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicHooksStudentOfMonthRoute: ApiPublicHooksStudentOfMonthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
